# Generated by Django 5.2.1 on 2025-06-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photolike',
            unique_together=set(),
        ),
    ]
