# Generated by Django 5.2.1 on 2025-06-12 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0010_alter_photo_category_alter_photo_tags_and_more'),
        ('Social', '0002_alter_photolike_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='photolike',
            constraint=models.UniqueConstraint(fields=('photo', 'user'), name='unique_photo_user_like'),
        ),
    ]
