# Generated by Django 5.2.1 on 2025-06-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='name',
            field=models.CharField(default='Photography', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Photography', max_length=100),
        ),
    ]
