# Generated by Django 5.2.1 on 2025-06-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0003_alter_category_name_alter_tags_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='photos.photo',
        ),
    ]
