# Generated by Django 5.2.1 on 2025-06-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0004_alter_photo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='photos_photo',
        ),
    ]
