# Generated by Django 5.2.1 on 2025-06-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0005_alter_photo_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterModelTable(
            name='photo',
            table=None,
        ),
    ]
