# Generated by Django 5.2.1 on 2025-06-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0007_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='mediafiles'),
        ),
    ]
