# Generated by Django 5.2.1 on 2025-06-17 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0011_savephotos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savephotos',
            constraint=models.UniqueConstraint(fields=('user', 'photo'), name='unique_save_photo'),
        ),
    ]
